# Generated by Django 3.1.4 on 2021-01-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210102_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=128, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=128, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='QQ账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女'), (0, '未知')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wc_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='微信账号'),
        ),
    ]
