# Generated by Django 3.1.4 on 2021-01-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210105_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '申请'), (1, '通过'), (2, '拒绝')], default=0, verbose_name='审核状态'),
        ),
    ]
